/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package htw.berlin.wi.prog2;

import htw.berlin.wi.prog2.service.SimpleInputParser;
import htw.berlin.wi.prog2.service.PizzaBuilder;
import htw.berlin.wi.prog2.ui.CommandLineUI;
import htw.berlin.wi.prog2.ui.UserInputWrapper;

public class PizzaBotApp {
    public static void main(String[] args) {
        SimpleInputParser parser = new SimpleInputParser();
        PizzaBuilder builder = new PizzaBuilder();
        UserInputWrapper wrapper = new UserInputWrapper(System.in, System.out);
        CommandLineUI clui = new CommandLineUI(wrapper, builder, parser);
        clui.launch();
    }
}
